site_name: Self-Organizing-Recurrent-Network-Simulator
site_url: ""
site_description: Project documentation with Markdown.
site_author: Marius Vieth

repo_url: https://github.com/gitmv/Self-Organizing-Recurrent-Network-Simulator
edit_uri: ""

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust

nav:
    - Home: index.md
    - Introduction:
        - Installation: Introduction/installation.md
        - Installation2: Introduction/installation2.md
    - Examples:
        - Example1: Examples/example1.md

plugins:
    - search